apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: airflow
data:
  GITSYNC_USERNAME: b3NlZ2hhbGVwYXRyaWNr
  GITSYNC_PASSWORD: Z2hwX2N5c2N4NGxQZVlXaWxOclV3OWJLbkZnQ2tISVU1UTE4N2tvSA==
  GIT_SYNC_USERNAME: b3NlZ2hhbGVwYXRyaWNr
  GIT_SYNC_PASSWORD: Z2hwX2N5c2N4NGxQZVlXaWxOclV3OWJLbkZnQ2tISVU1UTE4N2tvSA==
